import hashlib
import json
from pathlib import Path

from fastapi.testclient import TestClient
import pandas as pd

import marketleak.api as api
from marketleak.pipeline_v2 import PipelineV2Result
from marketleak.detectors import DetectionBatch
from datetime import datetime, timezone


NOW = datetime(2026, 1, 1, tzinfo=timezone.utc)


def v2_result() -> PipelineV2Result:
    return PipelineV2Result(
        run_uid="run:test",
        started_at=NOW,
        completed_at=NOW,
        status="completed_no_actionable_activity",
        data_quality={"gate_passed": True, "received": 0, "normalized": 0},
        detector_batch=DetectionBatch((), (), ()),
        assessments=(),
        actor_availability={"available": False},
        source_availability={"coverage_status": "unknown_coverage"},
        validation_status={"validated": False, "effectiveness_unknown": True},
    )


def write_truth_safe_memo(path: Path, body: str) -> None:
    metadata = {
        "schema_version": "marketleak.investigative-memo/v2",
        "artifact_type": "investigative_review_memo",
        "artifact_uid": "memo:" + "a" * 64,
        "source_uid": "marketleak:assessment/test",
        "generator_name": "marketleak.synthesis.truth-firewall",
        "generator_version": "2.0.0",
        "generated_at": "2026-01-01T00:00:00Z",
        "content_sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
        "not_proof_of_fraud": True,
        "effectiveness_unknown": True,
        "human_review_required": True,
    }
    path.write_text(
        "<!-- MARKETLEAK_ARTIFACT_METADATA_V2\n"
        + json.dumps(metadata, sort_keys=True, separators=(",", ":"))
        + "\n-->\n"
        + body,
        encoding="utf-8",
    )


def test_seven_v1_routes_and_errors_remain_compatible(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(api, "_global_v2_result", v2_result())
    monkeypatch.setattr(api, "_load_anomalies", lambda: pd.DataFrame())
    monkeypatch.setattr(api, "_load_feed", lambda: pd.DataFrame(columns=["market_slug", "question"]))
    monkeypatch.setattr(api, "REPORTS_DIR", tmp_path)
    client = TestClient(api.app)

    assert client.get("/api/health").json() == {"status": "ok"}

    anomalies = client.get("/api/anomalies").json()
    assert anomalies["count"] == 0
    assert anomalies["anomalies"] == []
    assert anomalies["assessment_v2"] == []
    assert anomalies["data_quality"]["gate_passed"] is True

    sweep = client.post("/api/analyze/sweep").json()
    assert sweep["results"] == []
    assert sweep["not_proof_of_fraud"] is True

    missing = client.post("/api/analyze/missing-market")
    assert missing.status_code == 404
    assert missing.json()["detail"] == "No anomalies are currently available."

    assert client.get("/api/reports").json() == {"reports": []}
    assert client.get("/api/reports/not-markdown.txt").status_code == 400

    mock_report = tmp_path / "legacy.md"
    mock_report.write_text("Source: https://news.mock/item\nGenerated by Mock LLM", encoding="utf-8")
    listed_report = client.get("/api/reports").json()["reports"][0]
    assert listed_report["filename"] == "legacy.md"
    assert listed_report["legacy_demo_artifact"] is True
    assert listed_report["evidence_classification"] == "quarantined_untrusted_artifact"
    assert listed_report["usable_as_validation_evidence"] is False
    assert listed_report["content_available"] is False
    assert listed_report["truth_firewall_verified"] is False
    fetched_report = client.get("/api/reports/legacy.md").json()
    assert fetched_report["content"].startswith("# Artifact quarantined")
    assert "news.mock" not in fetched_report["content"]
    assert "Mock LLM" not in fetched_report["content"]
    assert fetched_report["legacy_demo_artifact"] is True

    safe_body = (
        "# Investigative Review Memo (V2 / Unvalidated)\n\n"
        "## Observed fields\n\nA market timestamp was supplied for human review.\n"
    )
    safe_report = tmp_path / "verified.md"
    write_truth_safe_memo(safe_report, safe_body)
    safe_payload = client.get("/api/reports/verified.md").json()
    assert safe_payload["content"] == safe_body
    assert safe_payload["truth_firewall_verified"] is True
    assert safe_payload["content_available"] is True
    assert safe_payload["artifact_schema_version"] == "marketleak.investigative-memo/v2"

    tampered_report = tmp_path / "tampered.md"
    write_truth_safe_memo(tampered_report, safe_body)
    tampered_report.write_text(
        tampered_report.read_text(encoding="utf-8") + "Individuals likely traded on MNPI.\n",
        encoding="utf-8",
    )
    tampered_payload = client.get("/api/reports/tampered.md").json()
    assert tampered_payload["truth_firewall_verified"] is False
    assert "likely traded" not in tampered_payload["content"]

    unsafe_body = (
        "# Investigative Review Memo (V2 / Unvalidated)\n\n"
        "The analysis confirms that information leakage occurred.\n"
    )
    unsafe_report = tmp_path / "unsafe-marked.md"
    write_truth_safe_memo(unsafe_report, unsafe_body)
    unsafe_payload = client.get("/api/reports/unsafe-marked.md").json()
    assert unsafe_payload["truth_firewall_verified"] is False
    assert "information leakage occurred" not in unsafe_payload["content"]

    chat = client.post("/api/chat", json={"prompt": "Acme"}).json()
    assert chat["status"] == "not_found"
    assert chat["assessment_v2"] == []

    monkeypatch.setattr(
        api,
        "_load_feed",
        lambda: pd.DataFrame([{"market_slug": "acme", "question": "Will Acme happen?"}]),
    )
    normal = client.post("/api/chat", json={"prompt": "Acme"}).json()
    assert normal["status"] == "normal"
    assert normal["message"] == (
        "No validated activity signal is available; this is not evidence that trading was normal."
    )
    assert normal["scorable"] is None
    assert "causal history" in normal["limitations"]["scorable"]
    assert "Point-in-time" in normal["limitations"]["coverage"]

    assert client.post("/api/chat", json={"prompt": "   "}).status_code == 422
